# Generated by Django 3.1.7 on 2021-04-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='item',
            new_name='item_val',
        ),
    ]
